### ISSUE TITLE
duplicate a Book

### ISSUE THREAD

**Issue by andyhediger** [skodak/moodle-mod_book#21]
hello skodak 
and thank you for providing this module! it is very useful indeed: we are starting a "tips and hints for teachers" with it in switzerland

i have installed your latest code on our system Moodle 2.1.2+ (Build: 20111102)

Book    mod_book    Extension   2011110300  Enabled Enabled ----

when trying to "duplicate" our test book (i am doing this because i need to translate the german version to english)
i get the following error:
Coding error detected, it must be fixed by a programmer: Default theme standard not available or broken!

our selected theme is formfactor in this environment

i can of course "duplicate" it in another way, its just this functionality...

grüsse aus der Schweiz andy

**Comment by skodak** [comment]
I am not able to replicate this, sorry. In any case book does not deal with themes at all, it could be a problem elsewhere. You could try to enable the debug mode - you would get a detailed stack trace which may indicate where the problem actually is.
