### ISSUE TITLE
Importing book

### ISSUE THREAD

**Issue by FilipBenco** [skodak/moodle-mod_book#23]
I have a problem with Importing Book between Courses. Import does not copy book files into new course, so the links to that files are broken.

**Comment by skodak** [comment]
Hello, what moodle version, what book version, where are the files stored exactly?

**Comment by FilipBenco** [comment]
Moodle version 2.2, and book version - current MOODLE_22_STABLE,
Files are stored in course files.

Petr I found also another problem, this time with backup in 1.9 and restore in 2.2. The problem is, that ju didnt handle restore_decode_rule for BOOKSTART, you generate in moodle 1.9 backup for links to books. (line 123 in moodle 1.9/mod/book/backuplib.php). I fix this problem adding $rules[] = new restore_decode_rule('BOOKSTART', '/mod/book/view.php?id=$1', 'course_module'); in moodle22/mod/book/backup/moodle2/restore_book_activity_task.class.php in function define_decode_rules()
Just letting you know, so you can fix it for everybody:)

Filip

**Comment by skodak** [comment]
thanks for the info, hopefully I will find some time later this week to merge your fix, ciao

**Comment by stronk7** [comment]
Hi Petr, 

was this implemented fixed already? I'm moving issues here to the Tracker and it would be great to know. Ciao :-)

**Comment by skodak** [comment]
not fixed yet, please create a new issue in tracker if necessary, thanks

**Comment by stronk7** [comment]
This 2 issues have been created in the Tracker:
- Lost images on import: http://tracker.moodle.org/browse/MDL-33361
- BOOKSTART links not decoded on restore from 1.9 courses: http://tracker.moodle.org/browse/MDL-33362

So I think this can be closed here and continue being verified & fixes in the Tracker. Ciao :-)
