### ISSUE TITLE
upgradelib.php bug

### ISSUE THREAD

**Issue by t6nis** [skodak/moodle-mod_book#25]
Hi!

I encoutered a problem when upgrading moodle 1.9 to 2.2.

In book/db/upgradelib.php at line 101: book_migrate_moddata_dir_to_legacy($book, $context, $subpath);

it should be: mod_book_migrate_moddata_dir_to_legacy($book, $context, $subpath);

Then it is recursive or maybe i am missing something. Atleast i could'nt find any function named:

book_migrate_moddata_dir_to_legacy($book, $context, $subpath); 

Best,
T6nis

**Comment by skodak** [comment]
thanks for the report
