### ISSUE TITLE
SpellChecker in TineyMCE not updating word in IE

### ISSUE THREAD

**Issue by juliandavis71** [skodak/moodle-mod_book#26]
When running the spell checker in the TinyMCE editor in the Books Plugin, a misspelt word is detected. Left clicking allows you to select a word, but once you select the correctly spelt word, the misspelt word is NOT updated. 

This issue only appears in IE7, 8 and 9. When tested on other browsers (Windows 7 - Chrome 18.0.1025.162, Firefox 12, Opera 11.64 and Safari 5.1.7), the updating of the misspelt word works correctly.

Book Plugin version 2011101400 
TinyMCE version 2012030300 
Moodle 2.2.2+ (Build: 20120329)

**Comment by skodak** [comment]
Hello, this is most probably a problem in TinyMCE or the spellchecker plugin, not a book bug. Please try the latest 2.3dev with integrated book and report a new issue directly into tracker.moodle.org if necessary. Thanks for the report.
