### ISSUE TITLE
add option to (re)import individual chapters

### ISSUE THREAD

**Issue by skodak** [skodak/moodle-mod_book#9]
http://tracker.moodle.org/browse/CONTRIB-550

**Comment by stronk7** [comment]
Ho Petr, this seems to be simply cross-linked with CONTRIB-550 that was closed as dupe. Also, looking to code I've not been able to find any place where update is performed instead of insert.

So I should assume that this (nor CONTRIB-550) was ever implemented, correct?

Ciao :-)

**Comment by skodak** [comment]
reopened and moved to core - see MDL-33219, thanks
